import { faker } from "@faker-js/faker";

export const CATEGORIES = [
  "FOOD",
  "FASHION",
  "FITNESS",
  "PET",
  "CATEGORY5",
  "CATEGORY6",
  "CATEGORY7",
  "CATEGORY8",
  "CATEGORY9",
  "CATEGORY10",
];

export const VALUES = [
  "SUSTAINABLE",
  "ORGANIC",
  "RECYCLED",
  "VEGAN",
  "VALUE5",
  "VALUE6",
  "VALUE7",
  "VALUE8",
  "VALUE9",
  "VALUE10",
];

export const OBJECTIVES = [
  {
    key: "NEW",
    label: "I'm launching a new product or service",
    shortLabel: "New Product/Service",
  },
  {
    key: "AWARENESS",
    label: "I'm aiming to drive awareness about my product or service",
    shortLabel: "Awareness of Product/Service",
  },
  {
    key: "BASELINE",
    label: "I'm looking to develop baseline metrics",
    shortLabel: "Baseline Metrics",
  },
  {
    key: "SOURCING",
    label: "I'm sourcing content to use in my own channels",
    shortLabel: "Own Channel Sourcing",
  },
  {
    key: "PINFLUENCER",
    label: "I'm trialing influencer marketing or Pinfluencer",
    shortLabel: "Pinfluencer Trial",
  },
  { key: "OTHER", label: "Other", shortLabel: "" },
];

export const audienceAges = [
  {
    id: "audienceAge13To17Split",
    label: "13 to 17",
  },
  {
    id: "audienceAge18To24Split",
    label: "18 to 24",
  },
  {
    id: "audienceAge25To34Split",
    label: "25 to 34",
  },
  {
    id: "audienceAge35To44Split",
    label: "35 to 44",
  },
  {
    id: "audienceAge45To54Split",
    label: "45 to 55",
  },
  {
    id: "audienceAge55To64Split",
    label: "55 to 64",
  },
  {
    id: "audienceAge65PlusSplit",
    label: "64+",
  },
];
export const audienceGenders = [
  {
    id: "audienceFemaleSplit",
    label: "Female",
  },

  {
    id: "audienceMaleSplit",
    label: "Male",
  },
];

export const collaborations = [
  {
    id: 1,
    proposal: 1,
    state: "APPLIED",
    application: {
      details: faker.random.words(faker.random.numeric(2)),
      posts: 2,
      reels: 0,
    },
    influencer: 1,
  },
  {
    id: 4,
    proposal: 1,
    state: "APPLIED",
    application: {
      details: faker.random.words(faker.random.numeric(2)),
      posts: 0,
      reels: 1,
    },
    influencer: 4,
  },
  {
    id: 5,
    proposal: 1,
    state: "APPLIED",
    application: {
      details: faker.random.words(faker.random.numeric(2)),
      posts: 1,
      reels: 1,
    },
    influencer: 5,
  },
  {
    id: 2,
    proposal: 1,
    state: "APPROVED",
    application: {
      details: faker.random.words(faker.random.numeric(2)),
      posts: 3,
      reels: 0,
    },
    influencer: 2,
  },
  {
    id: 3,
    proposal: 1,
    state: "REJECTED",
    application: {
      details: faker.random.words(faker.random.numeric(2)),
      posts: 0,
      reels: 1,
    },
    influencer: 3,
  },
];

export const proposals = [
  {
    id: 1,
    title: "Organic Cocktails",
    creativeGuidance:
      "advice or information aimed at resolving a problem or difficulty, especially as given by someone in authority. eg He looked to his father for inspiration and guidance",
    name: "OrganiGin Cafe",
    image: faker.image.abstract(300, 300, true),
    values: ["SUSTAINABLE", "ORGANIC", "RECYCLED", "VEGAN"],
    categories: ["FOOD", "FASHION", "FITNESS", "PET", "CATEGORY5"],
    created: "2022-10-24T01:02:02.012Z",
    proposalMonth: "December",
    proposalYear: "2022",
  },
  {
    id: 2,
    title: "Proident quis esse sunt",
    creativeGuidance:
      "Cupidatat cillum ad deserunt sunt aliquip Lorem nostrud in non elit est amet in.",
    name: "Culpa nostrud eiusmod excepteur incididunt sint ea veniam incididunt ullamco quis ut amet amet veniam. Eiusmod ad eiusmod velit aliquip. Ipsum fugiat labore laborum eiusmod duis ex eu laboris incididunt non pariatur. Minim aliquip pariatur officia Lorem aliquip culpa anim occaecat duis labore laborum esse in minim.",
    image: "https://dummyimage.com/300",
    values: ["ORGANIC"],
    categories: ["FOOD"],
    created: "2022-10-21T11:22:32.012Z",
    proposalMonth: "November",
    proposalYear: "2022",
  },
  {
    id: 3,
    title: "Culpa nostrud",
    creativeGuidance: "Minim occaecat nisi veniam in nisi veniam nostrud.",
    name: "Culpa nostrud eiusmod excepteur incididunt sint ea ",
    image: "https://dummyimage.com/300",
    values: ["ORGANIC"],
    categories: ["FOOD"],
    created: "2022-09-29T09:22:32.012Z",
    proposalMonth: "Januaray",
    proposalYear: "2023",
  },
];

export const influencers = [
  {
    id: 1,
    givenName: "Harry",
    familyName: "Potter",
    email: "hp@hogwarts.wiz",
    instaHandle: "harry_scar",
    website: "https://hp.hogwarts.wiz",
    address: "4 Privit Drive, Surrey WD25 7LR",
    bio: "Harry James[58] Potter (b. 31 July 1980)[1] was an English half-blood[2] wizard, and one of the most famous wizards of modern times. The only child and son of James and Lily Potter (née Evans), Harry's birth was overshadowed by a prophecy, naming either himself or Neville Longbottom as the one with the power to vanquish Lord Voldemort, the most powerful and feared Dark Wizard in the world. After half of the prophecy was reported to Voldemort, courtesy of Severus Snape, Harry was chosen as the target due to his many similarities with the Dark Lord. In turn, this caused the Potter family to go into hiding.",
    image: faker.image.abstract(300, 300, true),
    audienceAge13To17Split: 10,
    audienceAge18To24Split: 10,
    audienceAge25To34Split: 10,
    audienceAge35To44Split: 20,
    audienceAge45To54Split: 20,
    audienceAge55To64Split: 20,
    audienceAge65PlusSplit: 10,
    audienceFemaleSplit: 50,
    audienceMaleSplit: 50,
    CATEGORIES: ["FOOD", "FASHION", "FITNESS"],
    VALUES: ["SUSTAINABLE", "ORGANIC", "RECYCLED", "VEGAN"],
  },
  {
    id: 2,
    givenName: faker.name.firstName(),
    familyName: faker.name.lastName(),
    email: faker.internet.email(),
    instaHandle: faker.name.middleName(),
    website: faker.internet.url(),
    address: faker.address.streetAddress(),
    bio: faker.random.words(45),
    image: faker.image.abstract(300, 300, true),
    audienceAge13To17Split: 10,
    audienceAge18To24Split: 10,
    audienceAge25To34Split: 10,
    audienceAge35To44Split: 20,
    audienceAge45To54Split: 20,
    audienceAge55To64Split: 20,
    audienceAge65PlusSplit: 10,
    audienceFemaleSplit: 50,
    audienceMaleSplit: 50,
    CATEGORIES: ["FOOD", "FASHION", "FITNESS"],
    VALUES: ["SUSTAINABLE", "ORGANIC", "RECYCLED", "VEGAN"],
  },
  {
    id: 3,
    givenName: faker.name.firstName(),
    familyName: faker.name.lastName(),
    email: faker.internet.email(),
    instaHandle: faker.name.middleName(),
    website: faker.internet.url(),
    address: faker.address.streetAddress(),
    bio: faker.random.words(45),
    image: faker.image.abstract(300, 300, true),
    audienceAge13To17Split: 10,
    audienceAge18To24Split: 10,
    audienceAge25To34Split: 10,
    audienceAge35To44Split: 20,
    audienceAge45To54Split: 20,
    audienceAge55To64Split: 20,
    audienceAge65PlusSplit: 10,
    audienceFemaleSplit: 50,
    audienceMaleSplit: 50,
    CATEGORIES: ["FOOD", "FASHION", "FITNESS"],
    VALUES: ["SUSTAINABLE", "ORGANIC", "RECYCLED", "VEGAN"],
  },
  {
    id: 4,
    givenName: faker.name.firstName(),
    familyName: faker.name.lastName(),
    email: faker.internet.email(),
    instaHandle: faker.name.middleName(),
    website: faker.internet.url(),
    address: faker.address.streetAddress(),
    bio: faker.random.words(45),
    image: faker.image.abstract(300, 300, true),
    audienceAge13To17Split: 10,
    audienceAge18To24Split: 10,
    audienceAge25To34Split: 10,
    audienceAge35To44Split: 20,
    audienceAge45To54Split: 20,
    audienceAge55To64Split: 20,
    audienceAge65PlusSplit: 10,
    audienceFemaleSplit: 50,
    audienceMaleSplit: 50,
    CATEGORIES: ["FOOD", "FASHION", "FITNESS"],
    VALUES: ["SUSTAINABLE", "ORGANIC", "RECYCLED", "VEGAN"],
  },
  {
    id: 5,
    givenName: faker.name.firstName(),
    familyName: faker.name.lastName(),
    email: faker.internet.email(),
    instaHandle: faker.name.middleName(),
    website: faker.internet.url(),
    address: faker.address.streetAddress(),
    bio: faker.random.words(45),
    image: faker.image.abstract(300, 300, true),
    audienceAge13To17Split: 10,
    audienceAge18To24Split: 10,
    audienceAge25To34Split: 10,
    audienceAge35To44Split: 20,
    audienceAge45To54Split: 20,
    audienceAge55To64Split: 20,
    audienceAge65PlusSplit: 10,
    audienceFemaleSplit: 50,
    audienceMaleSplit: 50,
    CATEGORIES: ["FOOD", "FASHION", "FITNESS"],
    VALUES: ["SUSTAINABLE", "ORGANIC", "RECYCLED", "VEGAN"],
  },
];
